PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT DATA{
sn:forum%subjectId%
    rdf:type snvoc:Forum ;
    snvoc:id "%forumId%"^^xsd:long ;
    snvoc:title "%forumTitle%" ;
    snvoc:creationDate "%creationDate%"^^xsd:dateTime .
  };
  INSERT {
    sn:forum%subjectId% snvoc:hasModerator sn:pers%moderatorPersonId% ;
} WHERE {
    sn:pers%moderatorPersonId% rdf:type snvoc:Person .
};
INSERT {
 sn:forum%subjectId% snvoc:hasTag ?tag .
}
WHERE{
    SELECT ?tag
           WHERE {
           ?tag snvoc:id ?tagId .
           ?tag rdf:type ?tagClass .
           ?tagClass rdf:type snvoc:TagClass .
           FILTER (?tagId in (%tagIds%)) .
           }
}
