PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select distinct ?directFriend  ?first ?last ?post ?content ?date
where {
    #?directFriend (snvoc:knows/snvoc:hasPerson)|^(snvoc:knows/snvoc:hasPerson) sn:pers%personId%.
    sn:pers%personId%  (snvoc:knows/snvoc:hasPerson) ?directFriend .
    ?directFriend ^snvoc:hasCreator ?post .
    ?directFriend snvoc:firstName ?first.
    ?directFriend snvoc:lastName ?last .
    {
        ?post snvoc:content ?content
    }
    union
    {
        ?post snvoc:imageFile ?content
    }
    ?post snvoc:creationDate ?date.
    filter (?date < "%maxDate%"^^xsd:dateTime).
    filter ( sn:pers%personId% != ?directFriend).
}
order by desc (?date) ?post
limit 20