PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX onto: <http://www.ontotext.com/path#>
SELECT ?distOrNotFound
WHERE {
    OPTIONAL {
        VALUES (?source ?destination) {
            (sn:pers%person1Id% sn:pers%person2Id%)
        }
           SERVICE <http://www.ontotext.com/path#search> {
                    <urn:path> onto:findPath onto:distance ;
                               onto:sourceNode ?source ;
                               onto:destinationNode ?destination ;
                               onto:distanceBinding ?dist ;
                               onto:bidirectional true;
                               onto:startNode ?start ;
                               onto:endNode ?fr .
                    SERVICE <urn:path> {
                          ?fr snvoc:knows/snvoc:hasPerson ?start.
                    }
                }
            }
            BIND ( IF (BOUND (?dist), ?dist, -1 )  as ?distOrNotFound  ) .
}