PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
INSERT {
    sn:forum%forumId% snvoc:hasMember _:hasMember .
    _:hasMember snvoc:hasPerson sn:pers%personId% ;
    snvoc:joinDate "%joinDate%"^^xsd:dateTime .
} WHERE{
      sn:pers%personId% rdf:type snvoc:Person .
      sn:forum%forumId% rdf:type snvoc:Forum .
 }