PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

INSERT {
    sn:pers%subjectId% snvoc:workAt ?work .
} WHERE {
    ?work snvoc:hasOrganisation ?organization ;
           snvoc:workFrom "%worksFromYear%"^^xsd:integer .
    ?organization rdf:type dbpedia-owl:Company ;
                  snvoc:id "%organizationId%"^^xsd:int .
};