PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX ofn:<http://www.ontotext.com/sparql/functions/>

select ?liker ?first ?last ?ldt ?post ?content ?lag ?is_new
where {
    ?post snvoc:hasCreator sn:pers%personId% .
    {
        {
            ?post snvoc:content ?content 
        } union {
            ?post snvoc:imageFile ?content
        }
    } .
    ?lk snvoc:hasPost ?post .
    ?liker snvoc:likes ?lk .
    ?liker snvoc:firstName ?first .
    ?liker snvoc:lastName ?last .
    ?post snvoc:creationDate ?dt .
    ?lk snvoc:creationDate ?ldt .
    
    sn:pers%personId% snvoc:knows ?likerNode.
    bind(if (exists{?likerNode snvoc:hasPerson ?liker}, 0, 1) as ?is_new).
    bind(ofn:minutesBetween(?dt, ?ldt) as ?lag).
}
order by desc (?ldt) ?liker
limit 20
