PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
INSERT
{
    sn:post%postId% rdf:type snvoc:Post ;
    snvoc:id "%postId%"^^xsd:long ;
    snvoc:imageFile "%imageFile%" ;
    snvoc:creationDate "%creationDate%"^^xsd:dateTime ;
    snvoc:locationIP "%locationIP%" ;
    snvoc:browserUsed "%browserUsed%" ;
    snvoc:content "%content%" ;
    snvoc:length "%length%"^^xsd:int .
    sn:post%postId% snvoc:language "%language%" ;
                            snvoc:isLocatedIn ?country ;
    snvoc:hasCreator sn:pers%authorPersonId% ;
    snvoc:hasTag ?tag .
    sn:forum%forumId% snvoc:containerOf sn:post%postId% .
}
WHERE {
    sn:pers%authorPersonId% rdf:type snvoc:Person .
    sn:forum%forumId% rdf:type snvoc:Forum.
    ?country rdf:type dbpedia-owl:Country .
    ?country snvoc:id  "%countryId%"^^xsd:int .
    {
               SELECT  ?tag
               WHERE {
                   ?tag snvoc:id ?tagId .
                   ?tag rdf:type ?tagClass .
                   ?tagClass rdf:type snvoc:TagClass .
                   FILTER (?tagId in (%tagIds%)) .
               }
           }
}