PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>

SELECT distinct ?repliedComment ?repliedCommentContent ?repliedCommentCreationDate ?replyAuthor ?replyAuthorFirstName
?replyAuthorLastName ?knowsAuthor
WHERE {
	?message snvoc:id "%messageId%"^^xsd:long ;
             snvoc:hasCreator ?messageAuthor .
    ?repliedComment snvoc:replyOf ?message .
   # ?replyMessage snvoc:id "%messageId%"^^xsd:long .
    ?repliedComment snvoc:content ?repliedCommentContent ;
    				snvoc:creationDate ?repliedCommentCreationDate ;
        			snvoc:hasCreator ?replyAuthor .
                   OPTIONAL {
                     ?messageAuthor snvoc:knows/snvoc:hasPerson ?replyAuthor .
                     BIND( "true"^^xsd:boolean AS ?isKnown ) .
                 }
                 BIND (IF((?replyAuthor != ?messageAuthor && COALESCE(?isKnown, false)), true, false) AS
              ?knowsAuthor)
       ?replyAuthor snvoc:firstName ?replyAuthorFirstName ;
                  snvoc:lastName ?replyAuthorLastName ;
                  snvoc:id ?replyAuthorId .
} ORDER BY DESC(?repliedCommentCreationDate) ?replyAuthorId