PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?creatorId ?creatorFirstName ?creatorLastName
WHERE {
	?message snvoc:id "%messageId%"^^xsd:long ;
            snvoc:hasCreator ?creatorId .
    ?creatorId snvoc:firstName ?creatorFirstName ;
    		  snvoc:lastName ?creatorLastName ;
}