PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

INSERT DATA {
    sn:comm%subjectId% rdf:type snvoc:Comment ;
    snvoc:id "%commentId%"^^xsd:long ;
    snvoc:creationDate "%creationDate%"^^xsd:dateTime ;
    snvoc:locationIP "%locationIP%" ;
    snvoc:browserUsed "%browserUsed%" ;
    snvoc:content "%content%" ;
    snvoc:length "%length%"^^xsd:int .
};
INSERT {  sn:comm%subjectId% snvoc:replyOf ?commOrPost .
} WHERE {
    BIND ( (IF (%replyToPostId% = -1,
                    sn:comm%replyToCommentId%,
                    sn:post%replyToPostId%
                   ))
                    AS ?commOrPost)
 BIND ((IF (00000001099511639206 = -1,
                    snvoc:Comment,
                    snvoc:Post
                   )) AS ?type)
          ?commOrPost rdf:type ?type .
};
INSERT{
   sn:comm%subjectId% snvoc:isLocatedIn ?country .
} WHERE {
    ?country rdf:type dbpedia-owl:Country .
    ?country snvoc:id  "%countryId%"^^xsd:int .
};
INSERT{
  sn:comm%subjectId% snvoc:hasCreator sn:pers%authorPersonId% .
} WHERE {
    ?person rdf:type snvoc:Person .
}