PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

INSERT {
    sn:pers%personId% rdf:type snvoc:Person ;
    snvoc:id "%personId%"^^xsd:long ;
    snvoc:firstName "%personFirstName%" ;
    snvoc:lastName "%personLastName%" ;
    snvoc:gender "%gender%" ;
    snvoc:birthday "%birthday%"^^xsd:date ;
    snvoc:locationIP "%locationIP%" ;
    snvoc:browserUsed "%locationIP%" ;
    snvoc:creationDate "%creationDate%"^^xsd:dateTime ;
    snvoc:isLocatedIn ?countryIri .
} WHERE {
    ?countryIri rdf:type dbpedia-owl:Country ;
    			snvoc:id "%cityId%"^^xsd:int .
};

INSERT DATA {
    sn:pers%personId% snvoc:email "%emails%" .
};

INSERT DATA {
    sn:pers%personId% snvoc:speaks "%languages%" .
};

INSERT {
    sn:pers%personId% snvoc:hasInterest ?tag .
} WHERE {
    ?tag snvoc:id "%tagIds%"^^xsd:int ;
   		 rdf:type ?tagClass .
    ?tagClass rdf:type snvoc:TagClass .
};

INSERT {
    sn:pers%personId% snvoc:snvoc:studyAt ?study .
} WHERE {
    ?study snvoc:hasOrganisation ?organization ;
           snvoc:classYear "%studiesFromYear%"^^xsd:integer .
    ?organization rdf:type dbpedia-owl:University ;
                  snvoc:id "%organizationId%"^^xsd:int .
};

INSERT {
    sn:pers%personId% snvoc:snvoc:workAt ?work .
} WHERE {
    ?work snvoc:hasOrganisation ?organization ;
           snvoc:workFrom "%worksFromYear%"^^xsd:integer .
    ?organization rdf:type dbpedia-owl:Company ;
                  snvoc:id "%organizationId%"^^xsd:int .
};