PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT {
    sn:comm%subjectId% snvoc:hasTag ?tag .
} WHERE {
    ?tag snvoc:id "%tagId%"^^xsd:int ;
   		 rdf:type ?tagClass .
    ?tagClass rdf:type snvoc:TagClass .
};