PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT
    (?fr AS ?friendId)
    (?last AS ?friendLastName)
    (MIN(?dist) AS ?distanceFromPerson)
    (?bday AS ?friendBirthday)
    (?since AS ?friendCreationDate)
    (?gen AS ?friendGender)
    (?browser AS ?friendBrowserUsed)
    (?locationIP AS ?friendLocationIp)
    (GROUP_CONCAT(?email;separator=", ") AS ?friendEmails)
    (GROUP_CONCAT(?lng;separator=", ") AS ?friendLanguages)
    (?based AS ?friendCityName)
    ?studies
    ?jobs
{
    {
        SELECT DISTINCT
            ?fr
        WHERE
        {
            ?fr a snvoc:Person . 
            ?fr snvoc:firstName "John" . 
            ?fr snvoc:id ?frId .
            sn:pers00000000000000000933 snvoc:id ?rootId .
            sn:pers00000000000000000933 ((snvoc:knows/snvoc:hasPerson)|^(snvoc:knows/snvoc:hasPerson))?/((snvoc:knows/snvoc:hasPerson)|^(snvoc:knows/snvoc:hasPerson))?/((snvoc:knows/snvoc:hasPerson)|^(snvoc:knows/snvoc:hasPerson)) ?fr .
            FILTER(?frId != ?rootId)
        }
    }    
    ?fr snvoc:id ?frId .
    ?fr snvoc:lastName ?last .
    ?fr snvoc:birthday ?bday . 
    ?fr snvoc:isLocatedIn ?basedURI . 
    ?basedURI foaf:name ?based .
    ?fr snvoc:creationDate ?since . 
    ?fr snvoc:gender ?gen . 
    ?fr snvoc:locationIP ?locationIP .
    ?fr snvoc:browserUsed ?browser .
    {   
        SELECT
            (?frInner AS ?frInnerEmail)
            (GROUP_CONCAT(?email;separator=", ") AS ?emails)
        {
            SELECT DISTINCT 
                ?frInner
                ?email
            {   
                ?frInner a snvoc:Person . 
                ?frInner snvoc:email ?email
            }
        }
        GROUP BY ?frInner
    }
    
    OPTIONAL {
        {
            SELECT
                (?frInner AS ?frInnerUni)
                (GROUP_CONCAT(CONCAT(?uniName, " ", xsd:string(?classYear), " ", ?uniCountry);separator=", ") AS ?studies)
            {
                SELECT DISTINCT 
                    ?frInner
                    ?uniName
                    ?classYear
                    ?uniCountry
                {   
                    ?frInner a snvoc:Person . 
                    ?frInner snvoc:studyAt ?study .
                    ?study snvoc:hasOrganisation ?uni .
                    ?uni foaf:name ?uniName .
                    ?study snvoc:classYear ?classYear .
                    ?uni snvoc:isLocatedIn/foaf:name ?uniCountry .
                }
            }
            GROUP BY ?frInner
        }
        ?frInnerUni snvoc:id ?frInnerUniId .
        FILTER( ?frId = ?frInnerUniId)
    }
    OPTIONAL {
        {
            SELECT
                (?frInner AS ?frInnerComp)
                (GROUP_CONCAT(CONCAT(?companyName, " ", xsd:string(?workFrom), " ", ?companyCountry);separator=", ") AS ?jobs)
            {
                SELECT DISTINCT 
                    ?frInner
                    ?companyName
                    ?workFrom
                    ?companyCountry
                {   
                    ?frInner a snvoc:Person .
                    ?frInner snvoc:workAt ?work .
                    ?work snvoc:hasOrganisation ?company .
                    ?work snvoc:workFrom ?workFrom .
                    ?company snvoc:isLocatedIn/foaf:name ?companyCountry .
                    ?company foaf:name ?companyName
                }
            }
            GROUP BY ?frInner
        } .
        ?fr snvoc:id ?frId .
        ?frInnerComp snvoc:id ?frInnerCompId .
        FILTER( ?frId = ?frInnerCompId)
    }
}
GROUP BY ?fr ?last ?bday ?since ?gen ?browser ?locationIP ?based ?studies ?jobs
ORDER BY ?distanceFromPerson ?last ?fr
LIMIT 20
