PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

select ?fr ?p_friendfirstname ?p_friendlastname
              (?k_since - xsd:dateTime("1970-01-01T00:00:00.000+00:00")) * 1000 as ?k_s
where {
  ?person snvoc:id %Id% .
  ?person snvoc:knows ?tmp .
  ?tmp snvoc:creationDate ?k_since .
  ?tmp snvoc:hasPerson ?fr .
  ?fr snvoc:firstName ?p_friendfirstname .
  ?fr snvoc:lastName ?p_friendlastname .
}
order by desc(4) 1
