PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT
    (?tagname AS ?tagName)
    (count(*) AS ?postCount)
WHERE {
    ?post a snvoc:Post . ?post snvoc:hasCreator ?fr .
    ?post snvoc:hasTag ?tag . ?tag foaf:name ?tagname .
    ?post snvoc:creationDate ?date . sn:pers$Person snvoc:knows ?fr .
    FILTER (?date >= $Date0 && ?date <= $Date0 + "P$DurationD"^^xsd:duration) .
    FILTER ( NOT EXISTS {
        sn:pers$Person snvoc:knows ?fr2 .
        ?post2 snvoc:hasCreator ?fr2 .
	    ?post2 a snvoc:Post .
	    ?post2 snvoc:hasTag ?tag .
        ?post2 snvoc:creationDate ?date2 .
	    FILTER (?date2 < $Date0)
    })
}
GROUP BY ?tagname
ORDER BY desc(?cnt) ?tagname
limit 10
