PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

INSERT 
{
    _:forum a snvoc:Forum .
    _:forum snvoc:id "$forumId"^^xsd:long .
    _:forum snvoc:title "$title"^^xsd:string .
    _:forum snvoc:hasTag ?tag .
    _:forum snvoc:hasModerator ?moderator .
}
WHERE 
{
    ?moderator a snvoc:Person .
    ?moderator snvoc:id "$personId"^^xsd:long .
    ?tag snvoc:id "$tagId"^^xsd:long
}
