PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT
    ?commentId
    ?commentContent
    ?commentCreationDate
    ?replyAuthorId
    ?replyAuthorFirstName
    ?replyAuthorLastName
    ?replyAuthorKnowsOriginalMessageAuthor
WHERE
{
    BIND( $messageId AS ?messageId )
    ?message snvoc:id ?messageId .
    ?message snvoc:hasCreator ?messageCreator .
    ?messageCreator snvoc:id ?messageCreatorId .
    ?comment snvoc:replyOf ?message .
    ?comment a snvoc:Comment .
    ?comment snvoc:id ?commentId .
    ?comment snvoc:content ?commentContent .
    ?comment snvoc:creationDate ?commentCreationDate .
    ?comment snvoc:hasCreator ?replyAuthor .
    ?replyAuthor snvoc:id ?replyAuthorId .
    ?replyAuthor snvoc:firstName ?replyAuthorFirstName .
    ?replyAuthor snvoc:lastName ?replyAuthorLastName .
    OPTIONAL {
        ?messageCreator ((snvoc:knows/snvoc:hasPerson)|^(snvoc:knows/snvoc:hasPerson)) ?replyAuthor .
        BIND( "true"^^xsd:boolean AS ?replyAuthorKnowsOriginalMessageAuthorInner ) .
    }
    BIND( COALESCE(?replyAuthorKnowsOriginalMessageAuthorInner, "false"^^xsd:boolean) AS ?replyAuthorKnowsOriginalMessageAuthor ) .
}
ORDER BY DESC(?commentCreationDate) ?replyAuthorId
