PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sn: <http://www.ldbc.eu/ldbc_socialnet/1.0/data/>
PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX sntag: <http://www.ldbc.eu/ldbc_socialnet/1.0/tag/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

select
  (?exp AS ?personId)
  (?first AS ?personFirstName)
  (?last AS ?personLastName)
  (group_concat(distinct ?tagname;separator=', ') AS ?tagNames)
  (count(distinct ?reply) AS ?replyCount)
where {
    sn:pers$Person snvoc:knows ?exp .
    ?exp snvoc:firstName ?first .
    ?exp snvoc:lastName ?last .
    ?reply snvoc:hasCreator ?exp . 
    ?reply snvoc:replyOf ?org_post .
    ?org_post a snvoc:Post .
    ?org_post snvoc:hasTag ?tag .
    ?tag foaf:name ?tagname .
    ?tag a ?type.
    ?type rdfs:subClassOf* ?type1 .
    ?type1 rdfs:label $TagType .
}
group by ?exp ?first ?last
order by desc(?cnt) ?exp
limit 20
