#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
    DROP DATABASE IF EXISTS ${POSTGRES_DB};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_USER};
	CREATE DATABASE ${POSTGRES_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
EOSQL